name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Image Tags
        id: determine_tags
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:stable" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF}" == "refs/heads/testing" ]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:alpha" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./source
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.determine_tags.outputs.tags }}
