name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./source
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ github.ref_name == 'main' && 'ghcr.io/' + github.repository_owner + '/' + github.event.repository.name + ':latest' || '' }}
            ${{ github.ref_name == 'main' && 'ghcr.io/' + github.repository_owner + '/' + github.event.repository.name + ':stable' || (github.ref_name == 'testing' && 'ghcr.io/' + github.repository_owner + '/' + github.event.repository.name + ':testing' || 'ghcr.io/' + github.repository_owner + '/' + github.event.repository.name + ':alpha') }}
